### ISSUE TITLE
pdf2csv-converter issue

### ISSUE THREAD

**Issue by Ntnu2014** [SahilChoudhary22/pdf2csv-converter#1]
I am having an issue with the pdf2csv-converter. I am following the path you described (README.md) but I got an error saying that my python (3) can not find and read the "pdf2csv.py" file I am not able to run it. So, what could be the reason?

**Comment by SahilChoudhary22** [comment]
> I am having an issue with the pdf2csv-converter. I am following the path you described (README.md) but I got an error saying that my python (3) can not find and read the "pdf2csv.py" file I am not able to run it. So, what could be the reason?

Hello, are you sure you've stated the right path of file? Can you post the screenshot of your error and the location of your 'pdf2csv.py' file?

Also, if you're sure that you are giving the right path, then (if on windows), open the folder of 'pdf2csv.py', go to top left, click file, click on 'Open Windows Powershell as administrator" and try running the code.
