### ISSUE TITLE
Which path in linux?

### ISSUE THREAD

**Issue by alelasantillan** [SahilChoudhary22/pdf2csv-converter#3]
I've installed poppler in linux but no idea what shoul be into the config.ini file as linux paths both for tesseract and for poppler.
Poppler is working since the test:
pdftoppm -h
works. But as no path is provided, the pdf2csv.py tells that poppler is not installed.
The same with tesseract, which I installed via pip. No idea about the path either.

Please adv.

**Comment by SahilChoudhary22** [comment]
Hi @alelasantillan,

Closing this because the project is now in a read-only mode and we won't be continuing the development here as there are better AI based alternatives available for the users. 🙇
